<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
	<array>
		<string>mclog</string>
	</array>
	<key>name</key>
	<string>MC Log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Format Date</string>
			<key>match</key>
			<string>[0-9]{4}-[0-9]{2}-[0-9]{2}.[0-9]{2}:[0-9]{2}:[0-9]{2}</string>
			<key>name</key>
			<string>constant.numeric.mclog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>User ID</string>
			<key>match</key>
			<string>&lt;.+ .+&gt;</string>
			<key>name</key>
			<string>entity.name.tag.mclog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>INFO MESSAGE</string>
			<key>match</key>
			<string>\[(Blacksmith|BOSsmith|BukkitCompat|Chat|ChestShop|CoreProtect|dynmap|Economy|Essentials|EssentialsAntiBuild|EssentialsChat|EssentialsGeoIP|EssentialsProtect|EssentialsSpawn|FoundDiamonds|GroupManager|INFO|LWC|MobArena|Permission|Permissions|Server|Sponsor|Vault|Votifier|WorldEdit|WorldGuard)\]</string>
			<key>name</key>
			<string>string.quoted.mclog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>warning</string>
			<key>match</key>
			<string>\[WARNING\] .+</string>
			<key>name</key>
			<string>invalid.illegal.mclog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>method</string>
			<key>match</key>
			<string> (meth|method55|method|METHOD|METHOD55) </string>
			<key>name</key>
			<string>invalid.illegal.mclog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.mclog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.mclog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.variable.mclog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Issued Command</string>
			<key>match</key>
			<string>(\w+) (issued server command:) (/.+)</string>
			<key>name</key>
			<string>support.function.mclog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>.mclog</string>
	<key>uuid</key>
	<string>91dd79c7-adef-43c9-84cf-fa90e5685d6d</string>
</dict>
</plist>
